version: '2'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    hostname: mysql
    ports:
        - "3366:3306"
    volumes:
      - "./volume/mysql:/var/lib/mysql"
    environment:
        - MYSQL_USER=root
        - MYSQL_PASSWORD=test
        - MYSQL_DATABASE=azkaban
        - MYSQL_ROOT_PASSWORD=test
    networks:
      - azk
    tty: true

  executor:
    image: azkaban-executor
    links:
        - mysql
    networks:
      - azk
    tty: true

  webserver:
    image: azkaban-webserver
    ports:
        - "8443:8443"
    links:
        - executor:azkaban-executor
        - mysql
    networks:
      - azk
    tty: true

networks:
  azk: