version: '2'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    hostname: mysql
    ports:
        - "3366:3306"
    volumes:
      - "./volume/mysql:/var/lib/mysql"
    environment:
        - MYSQL_USER=root
        - MYSQL_PASSWORD=test
        - MYSQL_DATABASE=azkaban
        - MYSQL_ROOT_PASSWORD=test
    networks:
      - azk
    tty: true

  executor:
    image: azkaban-exec:0.1.0-SNAPSHOT
    container_name: azkaban-exec
    links:
        - mysql
    networks:
      - azk
    tty: true

  webserver:
    image: azkaban-web:0.1.0-SNAPSHOT
    container_name: azkaban-web
    ports:
        - "8443:8443"
    links:
        - executor:azkaban-exec
        - mysql
    networks:
      - azk
    tty: true

networks:
  azk: